# Site settings
title: Course Notes
email: harveycabaguio@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Collection of notes for my courses.
baseurl: "/notes" # the subpath of your site, e.g. /blog
url: "http://harveycabaguio.github.io" # the base hostname & protocol for your site
github_username:  harveycabaguio

# Build settings
markdown: kramdown
